Repository shaarli/Shaarli, pull requests merged in 2018-07, with the labels that each got.

#1173 Docker: expose a volume for the thumbnail cache
  Dockerfile
  doc/md/docker/shaarli-images.md
Labels: docker, documentation, enhancement, in review, thumbnail

#1141 Implements Tags endpoints for Shaarli's REST API
  .htaccess
  application/api/ApiUtils.php
  application/api/controllers/Links.php
  application/api/controllers/Tags.php
  application/api/exceptions/ApiTagNotFoundException.php
  index.php
  tests/api/controllers/history/HistoryTest.php
  tests/api/controllers/info/InfoTest.php
  tests/api/controllers/links/DeleteLinkTest.php
  tests/api/controllers/links/GetLinkIdTest.php
  tests/api/controllers/links/GetLinksTest.php
  tests/api/controllers/links/PostLinkTest.php
  tests/api/controllers/links/PutLinkTest.php
  tests/api/controllers/tags/DeleteTagTest.php
  tests/api/controllers/tags/GetTagNameTest.php
  tests/api/controllers/tags/GetTagsTest.php
  tests/api/controllers/tags/PutTagTest.php
Labels: API, in review, tags

#1175 Include ProxyPreserveHost directive in Apache's proxy doc
  doc/md/docker/reverse-proxy-configuration.md
Labels: documentation, in review, server

#1178 Upgrade-and-migration.md: typo installation link
  doc/md/Upgrade-and-migration.md
Labels: documentation, in review

#1180 Bump the base Docker image to alpine:3.8
  Dockerfile
Labels: docker

#1176 Fix broken documentation links in page footer and pluginsadmin
  tpl/default/pluginsadmin.html
  tpl/vintage/page.footer.html
Labels: documentation

#1181 Documentation - REST API - Mention dev.debug mode
  doc/md/REST-API.md
Labels: API, documentation, in review

#1184 Disable MkDocs' strict mode for ReadTheDocs builds to pass
  mkdocs.yml
Labels: bug, documentation

#687 Use web-thumbnailer to retrieve thumbnails
  application/PageBuilder.php
  application/Router.php
  application/Thumbnailer.php
  application/Updater.php
  application/config/ConfigManager.php
  assets/common/js/picwall.js
  assets/common/js/thumbnails-update.js
  assets/common/js/thumbnails.js
  assets/default/scss/shaarli.scss
  assets/vintage/css/shaarli.css
  composer.json
  composer.lock
  doc/md/Link-structure.md
  doc/md/Server-configuration.md
  inc/languages/fr/LC_MESSAGES/shaarli.po
  inc/web-thumbnailer.json
  index.php
  mkdocs.yml
  tests/ThumbnailerTest.php
  tests/Updater/UpdaterTest.php
  tests/config/ConfigManagerTest.php
  tests/utils/config/configJson.json.php
  tests/utils/config/wt.json
  tpl/default/configure.html
  tpl/default/linklist.html
  tpl/default/page.header.html
  tpl/default/picwall.html
  tpl/default/thumbnails.html
  tpl/default/tools.html
  tpl/vintage/configure.html
  tpl/vintage/linklist.html
  tpl/vintage/picwall.html
  tpl/vintage/thumbnails.html
  webpack.config.js
Labels: 3rd party, documentation, in review, template, thumbnail

#1186 v0.10: changelog, authors and dependencies
  AUTHORS
  CHANGELOG.md
  composer.lock
Labels: project-related

#1188 Include assets in the release_archive Makefile target
  Makefile
Labels: bug, in review
