Repository shaarli/Shaarli, pull requests merged in 2018-02, with the labels that each got.

#1084 Documentation: cleanup, update references to config(.json)?.php
  doc/md/Directory-structure.md
  doc/md/Plugins.md
  doc/md/Troubleshooting.md
  doc/md/Upgrade-and-migration.md
Labels: documentation, in review

#1089 Update badges for 'stable'
  README.md
Labels: documentation

#1062 Use a specific page title in all pages
  application/config/ConfigManager.php
  inc/languages/fr/LC_MESSAGES/shaarli.po
  index.php
Labels: browser, enhancement, in review, tags

#1092 Ignore the case while checking DOCTYPE during the file import
  application/NetscapeBookmarkUtils.php
  tests/NetscapeBookmarkUtils/BookmarkImportTest.php
  tests/NetscapeBookmarkUtils/input/lowercase_doctype.htm
Labels: 3rd party, bug, tools

#1085 docker: introduce multi-stage image build (master, latest)
  docker/alpine/Dockerfile.latest
  docker/alpine/Dockerfile.master
Labels: docker, enhancement

#1090 Doxygen: ignore data/, simplify Make target
  Doxyfile
  Makefile
Labels: cleanup, in review
