Repository shaarli/Shaarli, pull requests merged in 2018-10, with the labels that each got.

#1220 add "noindex, nofollow" HTML robots meta-tag to documentation pages
  doc/custom_theme/main.html
  doc/md/Server-configuration.md
  mkdocs.yml
Labels: documentation, in review, server

#1212 Fix hashtags with markdown escape enabled
  plugins/markdown/markdown.php
  tests/plugins/PluginMarkdownTest.php
  tests/plugins/resources/hashtags.md
  tests/plugins/resources/hashtags.raw
  tests/plugins/resources/markdown.html
  tests/plugins/resources/markdown.md
Labels: bug, in review, plugin

#1211 Fix a bug making thumbnail to request the current page
  tpl/default/daily.html
  tpl/default/linklist.html
  tpl/default/picwall.html
  tpl/vintage/daily.html
  tpl/vintage/linklist.html
  tpl/vintage/picwall.html
Labels: bug, in review, template, thumbnail

#1208 Add a button to toggle all checkboxes of displayed links
  assets/default/js/base.js
  assets/default/scss/shaarli.scss
  tpl/default/linklist.html
  tpl/default/linklist.paging.html
Labels: enhancement, ergonomy, in review, thumbnail

#1205 Add OpenGraph meta tags on permalink page
  application/PageBuilder.php
  plugins/markdown/markdown.php
  tests/plugins/PluginMarkdownTest.php
  tpl/default/includes.html
  tpl/vintage/includes.html
Labels: feature, in review, template

#1231 Revert part of #1220
  doc/custom_theme/main.html
Labels: bug, documentation

#1221 doc: refactor documentation homepage
  doc/md/index.md
Labels: documentation, in review

#1232 remove firefox share documentation
  doc/md/Sharing-content.md
Labels: browser, documentation

#1230 Composer: bump netscape-bookmark-parser to 2.1
  composer.json
  composer.lock
Labels: tools

#1235 Dead link on dead link detector tool
  doc/md/Community-&-Related-software.md
Labels: 3rd party, documentation
