Repository shaarli/Shaarli, pull requests merged in 2018-03, with the labels that each got.

#1098 Fix permission issue introduced with multi-stage build
  docker/alpine/Dockerfile.latest
Labels: bug, docker

#1097 PSR: use elseif instead of else if
  application/FileUtils.php
  application/LinkFilter.php
  application/NetscapeBookmarkUtils.php
  application/Url.php
  application/api/controllers/History.php
  application/api/controllers/Links.php
  index.php
  tests/plugins/test/test.php
Labels: cleanup, in review

#1096 Make max download size and timeout configurable
  application/Updater.php
  index.php
  tests/Updater/UpdaterTest.php
Labels: enhancement, in review

#1102 Fix warning when trying to save redictor setting from the configure page
  index.php
Labels: bug, easy

#1100 Nginx logs to stdout for Docker images
  docker/alpine/Dockerfile.armhf.latest
  docker/alpine/Dockerfile.armhf.master
  docker/alpine/Dockerfile.latest
  docker/alpine/Dockerfile.master
Labels: docker, server, tools

#1108 fix: IP ban check for the Vintage theme
  tpl/vintage/loginform.html
Labels: bug, easy, template

#1109 Documentation : Fix current version file name
  doc/md/Upgrade-and-migration.md
Labels: documentation

#1107 httpd: always forward the 'Authorization' header
  .htaccess
Labels: enhancement, security, server

#1110 Documentation: release v0.9.6
  CHANGELOG.md
  README.md
  doc/md/Download-and-Installation.md
Labels: documentation

#1103 Fix removal of on=... attributes from html (generated from markdown)
  plugins/markdown/markdown.php
Labels: enhancement, in review, please test, plugin

#1093 Load theme translations files automatically
  application/Languages.php
  doc/md/Translations.md
  tests/LanguagesTest.php
  tests/languages/fr/LanguagesFrTest.php
  tests/utils/customtpl/dummy/language/fr/LC_MESSAGES/dummy.mo
  tests/utils/customtpl/dummy/language/fr/LC_MESSAGES/dummy.po
Labels: documentation, enhancement, in review, translations

#1115 Update parsedown to its latest version instead of fixed 1.6
  composer.json
  composer.lock
  tests/plugins/resources/markdown.html
Labels: 3rd party, security
