Repository shaarli/Shaarli, pull requests merged in 2018-04, with the labels that each got.

#1126 load user css at last, after plugin css to enable changing plugin styles
  tpl/default/includes.html
  tpl/vintage/includes.html
Labels: template

#1114 German language created
  application/Languages.php
  inc/languages/de/LC_MESSAGES/shaarli.po
Labels: in review, translations

#1081 doc: merge all sharing methods under a single "Sharing content" page
  doc/md/Bookmarklet.md
  doc/md/Firefox-share.md
  doc/md/Sharing-content.md
  doc/md/images/doc-logo.png
  doc/md/images/firefoxshare.png
  doc/md/images/install-shaarli.png
  doc/md/images/rss-filter-1.png
  doc/md/images/rss-filter-2.png
  doc/md/index.md
  inc/languages/fr/LC_MESSAGES/shaarli.po
  mkdocs.yml
  tpl/default/editlink.html
Labels: documentation
