Repository shaarli/Shaarli, pull requests merged in 2018-08, with the labels that each got.

#1195 Delete redundant titles
  tpl/default/tools.html
Labels: in review, template

#1199 Fix issue 'You are not authorized to add a link' with thumbnails enabled
  application/Updater.php
  index.php
Labels: bug, in review, thumbnail

#1200 Use version condition in the root .htaccess
  .htaccess
Labels: bug, in review, server

#1202 Upgrade composer - web-thumbnailer v1.3.0
  composer.lock
Labels: bug, in review, thumbnail

#1204 Fix docker build
  composer.lock
Labels: docker

#1193 Update French translation
  inc/languages/fr/LC_MESSAGES/shaarli.po
Labels: in review, translations
