Repository shaarli/Shaarli, pull requests merged in 2019-08, with the labels that each got.

#1340 doc: fix broken markdown link
  doc/md/Download-and-Installation.md
Labels: documentation

#1341 Remove Travis unit tests against PHP 5.6 and 7.0
  .travis.yml
Labels: php compatibility, project-related

#1342 Upgrade composer dependencies from PHP 7.1
  composer.json
  composer.lock
Labels: php compatibility, project-related

#1344 little fix template
  tpl/default/configure.html
Labels: template

#1345 Changelog v0.11.1
  AUTHORS
  CHANGELOG.md
Labels: project-related

#1350 Make sure that bookmark sort is consistent, even with equal timestamps
  application/bookmark/LinkDB.php
  tests/bookmark/LinkDBTest.php
Labels: enhancement, in review

#1336 ATOM Feed: use instance name as author name instead of URL
  tpl/default/feed.atom.html
  tpl/vintage/feed.atom.html
Labels: enhancement, in review

#1351 Bump PHP version check in index.php
  index.php
Labels: php compatibility

#1354 Fix image lazy loading issues
  assets/default/scss/shaarli.scss
Labels: bug, thumbnail

#1355 Markdown plugin: fix RSS feed direct link reverse
  plugins/markdown/markdown.php
  tests/plugins/PluginMarkdownTest.php
Labels: bug
