Repository shaarli/Shaarli, pull requests merged in 2019-02, with the labels that each got.

#1229 Run Shaarli's tests against PHP 7.3 RC1 on Travis
  .travis.yml
Labels: php compatibility, project-related

#1182 Do not check the IP address with session protection disabled
  application/security/LoginManager.php
  tests/security/LoginManagerTest.php
Labels: enhancement, ipv6, security

#1264 doc: fix invalid links
  doc/md/Shaarli-configuration.md
Labels: bug, documentation

#1268 Fix thumbnails disabling if PHP GD is not installed
  application/Thumbnailer.php
Labels: bug, in review

#1274 Fix button overlapping on mobile in linklist
  assets/default/scss/shaarli.scss
Labels: in review, template

#1269 Remove the redirector setting
  application/api/ApiMiddleware.php
  application/bookmark/LinkDB.php
  application/bookmark/LinkUtils.php
  application/config/ConfigManager.php
  application/feed/FeedBuilder.php
  application/updater/Updater.php
  doc/md/Shaarli-configuration.md
  index.php
  tests/bookmark/LinkDBTest.php
  tests/bookmark/LinkUtilsTest.php
  tests/plugins/PluginMarkdownTest.php
  tests/updater/UpdaterTest.php
Labels: cleanup, in review

#1270 Fix a warning if links sticky status isn't set
  application/bookmark/LinkDB.php
  index.php
Labels: bug, in review

#1275 Documentation: drop PHP 7.0 compatibility in Shaarli 11.x
  doc/md/Server-configuration.md
Labels: documentation, php compatibility

#1279 Update badges, changelog and documentation for v0.10.3
  CHANGELOG.md
  README.md
  doc/md/Download-and-Installation.md
Labels: documentation
