Repository shaarli/Shaarli, pull requests merged in 2019-03, with the labels that each got.

#1271 Do not try to retrieve thumbnails for internal link
  application/api/ApiUtils.php
  application/bookmark/LinkUtils.php
  application/feed/FeedBuilder.php
  application/netscape/NetscapeBookmarkUtils.php
  index.php
  tests/bookmark/LinkUtilsTest.php
Labels: enhancement, in review

#1272 Accessibility: specify the HTML lang attribute
  application/render/PageBuilder.php
  index.php
  tpl/default/404.html
  tpl/default/addlink.html
  tpl/default/changepassword.html
  tpl/default/changetag.html
  tpl/default/configure.html
  tpl/default/daily.html
  tpl/default/editlink.html
  tpl/default/export.html
  tpl/default/import.html
  tpl/default/install.html
  tpl/default/linklist.html
  tpl/default/loginform.html
  tpl/default/picwall.html
  tpl/default/pluginsadmin.html
  tpl/default/tag.cloud.html
  tpl/default/tag.list.html
  tpl/default/thumbnails.html
  tpl/default/tools.html
Labels: accessibility, in review, template

#1281 accessibility fixes
  tpl/default/linklist.html
  tpl/default/linklist.paging.html
  tpl/default/page.footer.html
  tpl/default/page.header.html
  tpl/default/tag.sort.html
Labels: accessibility, in review

#1288 docs: add readthedocs configuration file
  .readthedocs.yml
Labels: bug, documentation
