Repository shaarli/Shaarli, pull requests merged in 2019-01, with the labels that each got.

#1251 doc: update PHP compatibility table
  doc/md/Server-configuration.md
Labels: documentation, php compatibility

#1233 doc: fix homepage icon
  doc/md/images/icon.png
  doc/md/index.md
Labels: documentation

#1259 fix: ensure HTML tags are stripped from OpenGraph description
  tpl/default/includes.html
  tpl/vintage/includes.html
Labels: accessibility, bug, template

#1257 composer: enforce PHP security advisories
  composer.json
  composer.lock
Labels: in review, php compatibility, security, tools

#1258 Replace Doxygen with phpDocumentor to generate reference documentation
  .gitignore
  Doxyfile
  Makefile
  phpdoc.dist.xml
Labels: docker, documentation, in review, tools

#1262 Update Community-&-Related-software.md
  doc/md/Community-&-Related-software.md
Labels: 3rd party, documentation

#1261 Update Community-&-Related-software.md
  doc/md/Community-&-Related-software.md
Labels: 3rd party, documentation
