Repository shaarli/Shaarli, pull requests merged in 2019-09, with the labels that each got.

#1363 Fix undefined thumbnail in OpenGraph headers
  tpl/default/includes.html
  tpl/vintage/includes.html
Labels: bug, in review, thumbnail

#1364 Fix RSS permalink included in Markdown bloc
  application/feed/FeedBuilder.php
Labels: bug, in review

#1367 thumbnailer: add soundcloud.com to list of common media domains
  application/Thumbnailer.php
Labels: enhancement, in review, thumbnail

#1368 emojione & twemoji removed
  doc/md/Community-&-Related-software.md
Labels: documentation
