Repository shaarli/Shaarli, pull requests merged in 2019-07, with the labels that each got.

#1313 Automatically retrieve description for new bookmarks
  application/bookmark/LinkUtils.php
  application/config/ConfigManager.php
  doc/md/Shaarli-configuration.md
  inc/languages/fr/LC_MESSAGES/shaarli.po
  index.php
  tests/bookmark/LinkUtilsTest.php
  tpl/default/configure.html
  tpl/vintage/configure.html
Labels: feature, in review, template

#1320 a11y fix: label and tabindex
  tpl/default/loginform.html
Labels: accessibility, in review

#1322 fix a11y label
  tpl/default/changepassword.html
Labels: accessibility, in review

#1324 a11y fix add banner mobile version
  tpl/default/page.header.html
Labels: accessibility, in review

#1321 a11y fix img without alt
  tpl/default/404.html
Labels: accessibility, in review

#1323 fix a11y label
  tpl/default/changetag.html
Labels: accessibility, in review

#1317 Plugin to override default template colors
  .dev/.sasslintrc
  .gitignore
  assets/default/scss/shaarli.scss
  doc/md/Plugin-System.md
  doc/md/Plugins.md
  inc/languages/fr/LC_MESSAGES/shaarli.po
  index.php
  plugins/default_colors/default_colors.css.template
  plugins/default_colors/default_colors.meta
  plugins/default_colors/default_colors.php
  plugins/demo_plugin/demo_plugin.meta
  plugins/demo_plugin/demo_plugin.php
  tests/plugins/PluginDefaultColorsTest.php
Labels: in review, plugin, template

#1334 Changelog and authors for v0.11 release
  AUTHORS
  CHANGELOG.md
Labels: project-related

#1333 Persist sticky status on bookmark update
  index.php
Labels: bug, in review

#1327 a11y fixes
  tpl/default/import.html
  tpl/default/install.html
  tpl/default/linklist.html
  tpl/default/page.footer.html
  tpl/default/page.header.html
  tpl/default/picwall.html
  tpl/default/tag.cloud.html
  tpl/default/tag.list.html
Labels: accessibility, in review

#1337 Docker: Bump NodeJS version to prevent an issue with node-sass
  Dockerfile
Labels: docker
