Repository shaarli/Shaarli, pull requests merged in 2020-01, with the labels that each got.

#1358 Doc: add screenshots of all pages
  doc/md/index.md
Labels: documentation

#1353 Run Unit Tests against PHP 7.4
  .travis.yml
  application/ApplicationUtils.php
  application/api/ApiUtils.php
  composer.json
  composer.lock
  tests/ApplicationUtilsTest.php
  tests/PluginManagerTest.php
  tests/api/ApiUtilsTest.php
  tests/config/ConfigPhpTest.php
  tests/feed/CachedPageTest.php
  tests/updater/UpdaterTest.php
Labels: php compatibility, tools

#1398 Fix an issue with bookmark visibility filter
  index.php
Labels: bug

#1400 Ulauncher Extension
  doc/md/Community-&-Related-software.md
Labels: documentation

#1399 Fix an issue with private tags and fix nomarkdown tag
  application/bookmark/BookmarkFileService.php
  application/formatter/BookmarkDefaultFormatter.php
  application/formatter/BookmarkFormatter.php
  application/formatter/BookmarkMarkdownFormatter.php
  application/formatter/FormatterFactory.php
  index.php
  tests/bookmark/BookmarkFileServiceTest.php
  tests/feed/FeedBuilderTest.php
  tests/formatter/BookmarkDefaultFormatterTest.php
  tests/formatter/BookmarkMarkdownFormatterTest.php
  tests/formatter/BookmarkRawFormatterTest.php
  tests/formatter/FormatterFactoryTest.php
  tests/netscape/BookmarkExportTest.php
Labels: bug, in review

#1402 fix directory creation in makefile
  Makefile
Labels: bug, tools

#1408 Fix deprecated use of implode
  tpl/default/thumbnails.html
  tpl/vintage/thumbnails.html
Labels: bug, cleanup

#1406 Session cookie setting being set while session is active
  index.php
Labels: bug, in review

#1410 Rollback breaking change in REST API routes
  index.php
Labels: API, bug

#1411 Fix division by zero in tagcloud
  index.php
Labels: bug
