Repository shaarli/Shaarli, pull requests merged in 2020-05, with the labels that each got.

#1424 Add an exception to method 'whitelist_protocols' for url which started with '#'
  application/http/UrlUtils.php
Labels: enhancement

#1409 Process picwall rendering through Slim controller
  .editorconfig
  application/bookmark/Bookmark.php
  application/container/ContainerBuilder.php
  application/container/ShaarliContainer.php
  application/front/controllers/PictureWallController.php
  application/front/exceptions/ThumbnailsDisabledException.php
  application/legacy/LegacyUpdater.php
  application/updater/Updater.php
  assets/common/js/thumbnails-update.js
  assets/default/js/base.js
  doc/md/RSS-feeds.md
  doc/md/Translations.md
  index.php
  tests/container/ContainerBuilderTest.php
  tests/front/controller/PictureWallControllerTest.php
  tpl/default/changetag.html
  tpl/default/configure.html
  tpl/default/daily.html
  tpl/default/import.html
  tpl/default/includes.html
  tpl/default/linklist.html
  tpl/default/page.header.html
  tpl/default/picwall.html
  tpl/default/pluginsadmin.html
  tpl/default/tag.list.html
  tpl/default/tag.sort.html
  tpl/default/tools.html
  tpl/vintage/configure.html
  tpl/vintage/daily.html
  tpl/vintage/import.html
  tpl/vintage/includes.html
  tpl/vintage/page.header.html
  tpl/vintage/pluginsadmin.html
  tpl/vintage/tools.html
Labels: cleanup, enhancement, in review

#1407 Process logout through Slim controller
  application/bookmark/BookmarkFileService.php
  application/bookmark/BookmarkIO.php
  application/container/ContainerBuilder.php
  application/container/ShaarliContainer.php
  application/feed/Cache.php
  application/front/controllers/LogoutController.php
  application/legacy/LegacyLinkDB.php
  application/render/PageCacheManager.php
  index.php
  tests/bootstrap.php
  tests/container/ContainerBuilderTest.php
  tests/front/controller/LogoutControllerTest.php
  tests/legacy/LegacyLinkDBTest.php
  tests/render/PageCacheManagerTest.php
  tpl/default/page.header.html
  tpl/vintage/page.header.html
Labels: cleanup, enhancement, in review

#1461 Improve documentation about how to create and initialize a plugin
  doc/md/Plugin-System.md
Labels: documentation
