Repository shaarli/Shaarli, pull requests merged in 2020-09, with the labels that each got.

#1530 Fix broken route to filter not tagged bookmarks
  application/security/SessionManager.php
  index.php
  tests/security/SessionManagerTest.php
  tpl/default/linklist.paging.html
Labels: bug, in review

#1535 Export: refresh CRSF token after submit
  assets/default/js/base.js
Labels: bug, in review

#1534 Fix support for legacy route login redirection
  application/legacy/LegacyController.php
  tests/legacy/LegacyControllerTest.php
Labels: bug, in review

#1536 Fix login loop for private instances
  application/front/ShaarliMiddleware.php
Labels: bug, in review

#1524 Fixed: Pinned bookmarks are displayed first in ATOM/RSS feeds
  application/bookmark/BookmarkArray.php
  application/bookmark/BookmarkFileService.php
  application/bookmark/BookmarkServiceInterface.php
  application/feed/FeedBuilder.php
  tests/feed/FeedBuilderTest.php
Labels: bug, in review

#1520 Japanese translation: add language to admin configuration page
  application/Languages.php
  inc/languages/jp/LC_MESSAGES/shaarli.po
  tests/front/controller/admin/ConfigureControllerTest.php
Labels: in review, translations

#1523 Default colors plugin: generate CSS file during initialization
  plugins/default_colors/default_colors.php
  tests/plugins/PluginDefaultColorsTest.php
Labels: enhancement, in review, plugin

#1519 Default template: display pin button in mobile view
  tpl/default/linklist.html
Labels: in review, template

#1537 Plugin page targets: preserve backward compatibility
  application/front/controller/visitor/FeedController.php
  application/legacy/LegacyRouter.php
  tests/front/controller/visitor/FeedControllerTest.php
  tests/legacy/LegacyRouterTest.php
Labels: bug, in review

#1541 Fix: encoding in legacy route login redirection to post bookmark
  application/legacy/LegacyController.php
Labels: bug

#1538 Inject BookmarkServiceInterface in plugins data
  application/front/controller/admin/ShaarliAdminController.php
  application/front/controller/visitor/ShaarliVisitorController.php
  application/plugin/PluginManager.php
  doc/md/Plugin-System.md
Labels: enhancement, plugin

#1547 Fix visibility issue on daily page
  application/bookmark/BookmarkFileService.php
  application/bookmark/BookmarkFilter.php
  tests/bookmark/BookmarkFileServiceTest.php
  tests/bookmark/BookmarkFilterTest.php
Labels: bug, security

#1552 Improve default bookmarks after install
  application/bookmark/BookmarkInitializer.php
  inc/languages/fr/LC_MESSAGES/shaarli.po
  tests/bookmark/BookmarkFileServiceTest.php
  tests/bookmark/BookmarkInitializerTest.php
Labels: enhancement, in review

#1389 doc: rework installation/setup guides, general refactoring
  .htaccess
  .travis.yml
  doc/md/3rd-party-libraries.md
  doc/md/Backup-and-restore.md
  doc/md/Browsing-and-searching.md
  doc/md/Community-and-related-software.md
  doc/md/Continuous-integration-tools.md
  doc/md/Development-guidelines.md
  doc/md/Directory-structure.md
  doc/md/Docker.md
  doc/md/Download-and-Installation.md
  doc/md/FAQ.md
  doc/md/Installation.md
  doc/md/Link-structure.md
  doc/md/Plugins.md
  doc/md/REST-API.md
  doc/md/RSS-feeds.md
  doc/md/Release-Shaarli.md
  doc/md/Reverse-proxy.md
  doc/md/Security.md
  doc/md/Server-configuration.md
  doc/md/Server-security.md
  doc/md/Shaarli-configuration.md
  doc/md/Sharing-content.md
  doc/md/Static-analysis.md
  doc/md/Troubleshooting.md
  doc/md/Unit-tests.md
  doc/md/Upgrade-and-migration.md
  doc/md/Usage.md
  doc/md/dev/Development.md
  doc/md/dev/GnuPG-signature.md
  doc/md/dev/Plugin-system.md
  doc/md/dev/Release-Shaarli.md
  doc/md/dev/Theming.md
  doc/md/dev/Translations.md
  doc/md/dev/Unit-tests.md
  doc/md/dev/Versioning.md
  doc/md/dev/images/poedit-1.jpg
  doc/md/docker/docker-101.md
  doc/md/docker/resources.md
  doc/md/docker/reverse-proxy-configuration.md
  doc/md/docker/shaarli-images.md
  doc/md/guides/backup-restore-import-export.md
  doc/md/guides/images/01-create-droplet-distro.jpg
  doc/md/guides/images/02-create-droplet-region.jpg
  doc/md/guides/images/03-create-droplet-size.jpg
  doc/md/guides/images/04-finalize.jpg
  doc/md/guides/images/05-droplet.jpg
  doc/md/guides/images/06-domain.jpg
  doc/md/guides/install-shaarli-with-debian9-and-docker.md
  doc/md/guides/various-hacks.md
  doc/md/images/07-installation.jpg
  doc/md/images/bookmarklet.png
  doc/md/images/firefoxshare.png
  doc/md/images/install-shaarli.png
  doc/md/index.md
  mkdocs.yml
  plugins/playvideos/README.md
Labels: documentation, in progress, server

#1551 Plugins: do not save metadata along plugin parameters
  application/front/controller/admin/PluginsController.php
  application/plugin/PluginManager.php
  tests/PluginManagerTest.php
  tests/front/controller/admin/PluginsControllerTest.php
  tests/plugins/test/test.php
Labels: bug, in review, plugin

#1553 Properly handle 404 errors
  application/container/ContainerBuilder.php
  application/container/ShaarliContainer.php
  application/front/controller/visitor/ErrorNotFoundController.php
  tests/container/ContainerBuilderTest.php
  tests/front/controller/visitor/ErrorNotFoundControllerTest.php
  tests/front/controller/visitor/FrontControllerMockHelper.php
Labels: enhancement

#1556 Add PATCH to the allowed Apache request methods
  .htaccess
Labels: bug, in review, server

#1539 Add manual configuration for root URL
  application/feed/FeedBuilder.php
  application/front/controller/visitor/DailyController.php
  application/http/HttpUtils.php
  doc/md/Shaarli-configuration.md
  index.php
  tests/feed/FeedBuilderTest.php
  tests/front/controller/admin/ExportControllerTest.php
  tests/front/controller/admin/ToolsControllerTest.php
  tests/front/controller/visitor/DailyControllerTest.php
  tests/front/controller/visitor/FrontControllerMockHelper.php
  tests/front/controller/visitor/InstallControllerTest.php
  tests/front/controller/visitor/OpenSearchControllerTest.php
  tests/http/HttpUtils/IndexUrlTest.php
  tests/http/HttpUtils/IndexUrlTestWithConstant.php
Labels: enhancement, in review

#1559 Fix redirection to referer after editing a link
  application/front/controller/admin/ManageShaareController.php
Labels: bug

#1561 Upgrade front end dependencies
  .dev/.sasslintrc
  .dev/.stylelintrc.js
  .travis.yml
  Makefile
  assets/default/js/base.js
  assets/default/scss/shaarli.scss
  assets/vintage/css/shaarli.css
  package.json
  webpack.config.js
  yarn.lock
Labels: dependencies, enhancement, in review, security

#1565 Makefile: remove static_analysis_summary from all: target
  Makefile
Labels: bug, tools

#1558 Fix plugin base path in core plugins
  doc/md/dev/Plugin-system.md
  plugins/archiveorg/archiveorg.php
  plugins/isso/isso.php
  plugins/qrcode/qrcode.php
  tests/plugins/PluginArchiveorgTest.php
  tests/plugins/PluginIssoTest.php
  tpl/vintage/linklist.paging.html
Labels: bug, documentation, in review, plugin

#1560 Fix invalid redirection using the path of an external domain
  application/front/controller/visitor/ShaarliVisitorController.php
  tests/front/controller/admin/ManageShaareControllerTest/SaveBookmarkTest.php
  tests/front/controller/admin/SessionFilterControllerTest.php
  tests/front/controller/visitor/PublicSessionFilterControllerTest.php
  tests/front/controller/visitor/ShaarliVisitorControllerTest.php
Labels: bug

#1568 Fix undefined linkdate variable in vintage theme
  tpl/vintage/editlink.html
Labels: bug, in review, template

#1572 Run unit tests against multiple versions of PHPUnit
  .travis.yml
  composer.json
  tests/ApplicationUtilsTest.php
  tests/FileUtilsTest.php
  tests/HistoryTest.php
  tests/LanguagesTest.php
  tests/ThumbnailerTest.php
  tests/TimeZoneTest.php
  tests/UtilsTest.php
  tests/api/ApiMiddlewareTest.php
  tests/api/ApiUtilsTest.php
  tests/api/controllers/history/HistoryTest.php
  tests/api/controllers/info/InfoTest.php
  tests/api/controllers/links/DeleteLinkTest.php
  tests/api/controllers/links/GetLinkIdTest.php
  tests/api/controllers/links/GetLinksTest.php
  tests/api/controllers/links/PostLinkTest.php
  tests/api/controllers/links/PutLinkTest.php
  tests/api/controllers/tags/DeleteTagTest.php
  tests/api/controllers/tags/GetTagNameTest.php
  tests/api/controllers/tags/GetTagsTest.php
  tests/api/controllers/tags/PutTagTest.php
  tests/bookmark/BookmarkArrayTest.php
  tests/bookmark/BookmarkFileServiceTest.php
  tests/bookmark/BookmarkFilterTest.php
  tests/config/ConfigJsonTest.php
  tests/config/ConfigManagerTest.php
  tests/config/ConfigPhpTest.php
  tests/config/ConfigPluginTest.php
  tests/feed/CachedPageTest.php
  tests/formatter/BookmarkDefaultFormatterTest.php
  tests/formatter/BookmarkMarkdownFormatterTest.php
  tests/formatter/BookmarkRawFormatterTest.php
  tests/formatter/FormatterFactoryTest.php
  tests/languages/fr/LanguagesFrTest.php
  tests/legacy/LegacyLinkDBTest.php
  tests/legacy/LegacyLinkFilterTest.php
  tests/legacy/LegacyUpdaterTest.php
  tests/netscape/BookmarkExportTest.php
  tests/netscape/BookmarkImportTest.php
  tests/plugins/PluginAddlinkTest.php
  tests/plugins/PluginDefaultColorsTest.php
  tests/plugins/PluginPlayvideosTest.php
  tests/plugins/PluginPubsubhubbubTest.php
  tests/plugins/PluginQrcodeTest.php
  tests/plugins/PluginWallabagTest.php
  tests/plugins/WallabagInstanceTest.php
  tests/render/PageCacheManagerTest.php
  tests/security/BanManagerTest.php
  tests/security/LoginManagerTest.php
  tests/security/SessionManagerTest.php
  tests/updater/UpdaterTest.php
Labels: php compatibility, tools

#1566 doc/Makefile: remove references to composer update
  Makefile
  doc/md/dev/Unit-tests.md
Labels: documentation, tools

#1569 Fix warning if the encoding retrieved from external headers is invalid
  application/bookmark/LinkUtils.php
  application/front/controller/admin/ManageShaareController.php
  tests/bookmark/LinkUtilsTest.php
Labels: bug

#1576 Update CHANGELOG and AUTHOR
  .github/mailmap
  AUTHORS
  CHANGELOG.md
Labels: project-related
