Repository shaarli/Shaarli, pull requests merged in 2020-10, with the labels that each got.

#1577 Fix a bug preventing to edit bookmark with ID #0
  application/front/controller/admin/ManageShaareController.php
  tests/front/controller/admin/ManageShaareControllerTest/SaveBookmarkTest.php
Labels: bug

#1574 Workaround for hoster (ionos)
  .htaccess
  application/api/ApiMiddleware.php
  tests/api/ApiMiddlewareTest.php
Labels: API, in review, server

#1581 docker-compose.yml: pin traefik image to 1.7-alpine
  docker-compose.yml
Labels: bug, docker, proxy

#1579 Issue #1437 - Make tag cloud/list views buttons more obvious
  assets/default/scss/shaarli.scss
  tpl/default/tag.sort.html
Labels: ergonomy, in review, template

#1585 Security: fix multiple XSS vulnerabilities + fix search tags with special chars
  application/Utils.php
  application/formatter/BookmarkFormatter.php
  application/front/controller/admin/ManageShaareController.php
  application/front/controller/admin/ManageTagController.php
  application/front/controller/visitor/BookmarkListController.php
  application/front/controller/visitor/TagCloudController.php
  application/render/PageBuilder.php
  assets/default/js/base.js
  tpl/default/linklist.html
  tpl/default/tag.cloud.html
  tpl/default/tag.list.html
Labels: bug, security

#1586 CHANGELOG and AUTHORS for v0.12.0-beta-2
  AUTHORS
  CHANGELOG.md
Labels: project-related

#1589 CHANGELOG and AUTHORS for v0.12.0
  AUTHORS
  CHANGELOG.md
Labels: project-related

#1521 Add Markdown Extra formatter
  application/formatter/BookmarkMarkdownExtraFormatter.php
  application/front/controller/admin/ConfigureController.php
  composer.json
  composer.lock
  tests/formatter/BookmarkMarkdownExtraFormatterTest.php
  tests/front/controller/admin/ConfigureControllerTest.php
  tpl/default/includes.html
Labels: feature, in review

#1525 REST API: allow override of creation and update dates
  application/api/ApiUtils.php
  application/api/controllers/ApiController.php
  application/api/controllers/Links.php
  tests/api/controllers/links/PostLinkTest.php
Labels: API, feature, in review

#1540 Improve regex to extract HTML metadata (title, description, etc.)
  application/bookmark/LinkUtils.php
  tests/bookmark/LinkUtilsTest.php
Labels: enhancement, in review

#1570 Add mutex on datastore I/O operations
  application/api/ApiMiddleware.php
  application/bookmark/BookmarkFileService.php
  application/bookmark/BookmarkIO.php
  application/bookmark/BookmarkServiceInterface.php
  application/container/ContainerBuilder.php
  composer.json
  composer.lock
  init.php
  tests/api/controllers/info/InfoTest.php
  tests/api/controllers/links/DeleteLinkTest.php
  tests/api/controllers/links/GetLinkIdTest.php
  tests/api/controllers/links/GetLinksTest.php
  tests/api/controllers/links/PostLinkTest.php
  tests/api/controllers/links/PutLinkTest.php
  tests/api/controllers/tags/DeleteTagTest.php
  tests/api/controllers/tags/GetTagNameTest.php
  tests/api/controllers/tags/GetTagsTest.php
  tests/api/controllers/tags/PutTagTest.php
  tests/bookmark/BookmarkFileServiceTest.php
  tests/bookmark/BookmarkFilterTest.php
  tests/bookmark/BookmarkInitializerTest.php
  tests/bootstrap.php
  tests/feed/FeedBuilderTest.php
  tests/netscape/BookmarkExportTest.php
  tests/netscape/BookmarkImportTest.php
  tests/updater/UpdaterTest.php
Labels: enhancement, in review, performance, please test

#1583 Add strict types for bookmarks management
  application/api/ApiUtils.php
  application/api/controllers/Links.php
  application/bookmark/Bookmark.php
  application/bookmark/BookmarkArray.php
  application/bookmark/BookmarkFileService.php
  application/bookmark/BookmarkFilter.php
  application/bookmark/BookmarkIO.php
  application/bookmark/BookmarkInitializer.php
  application/bookmark/BookmarkServiceInterface.php
  application/feed/FeedBuilder.php
  application/front/controller/admin/ThumbnailsController.php
  application/security/LoginManager.php
  tests/HistoryTest.php
  tests/bookmark/BookmarkArrayTest.php
  tests/bookmark/BookmarkFileServiceTest.php
  tests/bookmark/BookmarkTest.php
  tests/front/controller/admin/ManageShaareControllerTest/DeleteBookmarkTest.php
  tests/front/controller/admin/ManageShaareControllerTest/SaveBookmarkTest.php
  tests/front/controller/admin/ThumbnailsControllerTest.php
Labels: cleanup, in review

#1591 Doc: add PHP 7.4 and 8.0 as supported version
  doc/md/Server-configuration.md
Labels: documentation

#1592 Strict types: fix an issue in daily where the date could be an int
  application/bookmark/BookmarkFileService.php
  tests/bookmark/BookmarkFileServiceTest.php
Labels: bug

#1593 Support using Shaarli without URL rewriting
  application/front/controller/visitor/ShaarliVisitorController.php
  application/plugin/PluginManager.php
  application/render/PageBuilder.php
  doc/md/Server-configuration.md
  doc/md/dev/Plugin-system.md
  plugins/archiveorg/archiveorg.php
  plugins/isso/isso.php
  plugins/qrcode/qrcode.php
  plugins/wallabag/wallabag.php
  tpl/default/daily.html
  tpl/default/includes.html
  tpl/default/linklist.html
  tpl/default/page.footer.html
  tpl/default/picwall.html
  tpl/default/pluginsadmin.html
Labels: enhancement, in review, server

#1596 Improve Manage tags page
  assets/default/js/base.js
  inc/languages/fr/LC_MESSAGES/shaarli.po
  tpl/default/changetag.html
  tpl/default/page.footer.html
Labels: enhancement, in review, tags

#1588 Feature: highlight fulltext search results
  application/bookmark/Bookmark.php
  application/bookmark/BookmarkFilter.php
  application/formatter/BookmarkDefaultFormatter.php
  application/formatter/BookmarkFormatter.php
  application/formatter/BookmarkMarkdownFormatter.php
  assets/default/scss/shaarli.scss
  tests/api/controllers/links/GetLinksTest.php
  tests/bookmark/BookmarkFileServiceTest.php
  tests/bookmark/BookmarkFilterTest.php
  tests/formatter/BookmarkDefaultFormatterTest.php
  tests/legacy/LegacyLinkDBTest.php
  tests/utils/ReferenceLinkDB.php
  tpl/default/linklist.html
Labels: feature, filter, in review, template

#1567 Add a setting to retrieve bookmark metadata asynchrounously
  Makefile
  application/config/ConfigManager.php
  application/container/ContainerBuilder.php
  application/container/ShaarliContainer.php
  application/front/controller/admin/ManageShaareController.php
  application/front/controller/admin/MetadataController.php
  application/http/HttpAccess.php
  application/http/HttpUtils.php
  application/http/MetadataRetriever.php
  assets/common/js/metadata.js
  assets/default/js/base.js
  assets/default/scss/shaarli.scss
  doc/md/Shaarli-configuration.md
  index.php
  package.json
  tests/bookmark/LinkUtilsTest.php
  tests/container/ContainerBuilderTest.php
  tests/front/controller/admin/ManageShaareControllerTest/DisplayCreateFormTest.php
  tests/http/MetadataRetrieverTest.php
  tpl/default/editlink.html
  webpack.config.js
  yarn.lock
Labels: feature, in review, performance, template

#1584 Asynchronous retrieval of bookmark's thumbnails
  application/bookmark/Bookmark.php
  application/front/controller/admin/ManageShaareController.php
  application/front/controller/visitor/BookmarkListController.php
  assets/common/js/metadata.js
  tests/bookmark/BookmarkTest.php
  tests/front/controller/admin/ManageShaareControllerTest/DisplayCreateFormTest.php
  tests/front/controller/admin/ManageShaareControllerTest/SaveBookmarkTest.php
  tests/front/controller/visitor/BookmarkListControllerTest.php
  tpl/default/linklist.html
  tpl/vintage/linklist.html
Labels: feature, in review, template, thumbnail

#1602 Dislay an error if an exception occurs in the error handler
  application/Utils.php
  application/front/controller/visitor/ErrorController.php
  index.php
Labels: bug, in review

#1605 Fix: nginx - add rule to disable url-rewriting for the docs
  .docker/nginx.conf
  doc/md/Server-configuration.md
Labels: server

#1601 Use PSR-3 logger for login attempts
  application/Utils.php
  application/container/ContainerBuilder.php
  application/container/ShaarliContainer.php
  application/front/controller/visitor/LoginController.php
  application/render/PageBuilder.php
  application/security/BanManager.php
  application/security/LoginManager.php
  composer.json
  composer.lock
  index.php
  tests/UtilsTest.php
  tests/container/ContainerBuilderTest.php
  tests/front/controller/visitor/LoginControllerTest.php
  tests/security/BanManagerTest.php
  tests/security/LoginManagerTest.php
  tests/security/SessionManagerTest.php
  tests/utils/FakeConfigManager.php
Labels: enhancement, in review

#1609 Removed PHP_EOL in configuration file
  application/config/ConfigJson.php
Labels: bug, in review

#1604 Feature: add a Server administration page
  application/ApplicationUtils.php
  application/FileUtils.php
  application/front/controller/admin/ServerController.php
  application/front/controller/visitor/BookmarkListController.php
  application/front/controller/visitor/InstallController.php
  assets/default/scss/shaarli.scss
  inc/languages/fr/LC_MESSAGES/shaarli.po
  index.php
  tests/ApplicationUtilsTest.php
  tests/FileUtilsTest.php
  tests/front/controller/admin/ServerControllerTest.php
  tests/front/controller/visitor/InstallControllerTest.php
  tpl/default/install.html
  tpl/default/server.html
  tpl/default/server.requirements.html
  tpl/default/tools.html
Labels: feature, in review, template

#1597 Feature: Share private bookmarks using a URL containing a private key
  application/bookmark/BookmarkFileService.php
  application/bookmark/BookmarkServiceInterface.php
  application/front/controller/admin/ManageShaareController.php
  application/front/controller/visitor/BookmarkListController.php
  inc/languages/fr/LC_MESSAGES/shaarli.po
  index.php
  tests/bookmark/BookmarkFileServiceTest.php
  tests/front/controller/admin/ManageShaareControllerTest/SharePrivateTest.php
  tests/front/controller/visitor/BookmarkListControllerTest.php
  tpl/default/linklist.html
Labels: feature, in review

#1595 Feature: add weekly and monthly view/RSS feed for daily page
  application/History.php
  application/Utils.php
  application/bookmark/BookmarkFileService.php
  application/bookmark/BookmarkServiceInterface.php
  application/front/controller/admin/ServerController.php
  application/front/controller/visitor/DailyController.php
  application/front/controller/visitor/InstallController.php
  application/helper/ApplicationUtils.php
  application/helper/DailyPageHelper.php
  application/helper/FileUtils.php
  application/legacy/LegacyLinkDB.php
  application/legacy/LegacyUpdater.php
  application/render/PageBuilder.php
  application/security/BanManager.php
  composer.json
  inc/languages/fr/LC_MESSAGES/shaarli.po
  init.php
  tests/bookmark/BookmarkFileServiceTest.php
  tests/front/controller/visitor/DailyControllerTest.php
  tests/helper/ApplicationUtilsTest.php
  tests/helper/DailyPageHelperTest.php
  tests/helper/FileUtilsTest.php
  tests/security/BanManagerTest.php
  tests/utils/FakeApplicationUtils.php
  tests/utils/ReferenceHistory.php
  tpl/default/daily.html
  tpl/default/dailyrss.html
Labels: feature, in review

#1587 Feature: bulk creation of bookmarks
  application/front/controller/admin/ManageShaareController.php
  application/front/controller/admin/ShaareAddController.php
  application/front/controller/admin/ShaareManageController.php
  application/front/controller/admin/ShaarePublishController.php
  application/render/TemplatePage.php
  assets/common/js/metadata.js
  assets/common/js/shaare-batch.js
  assets/default/js/base.js
  assets/default/scss/shaarli.scss
  inc/languages/fr/LC_MESSAGES/shaarli.po
  index.php
  tests/front/controller/admin/ManageShaareControllerTest/AddShaareTest.php
  tests/front/controller/admin/ShaareAddControllerTest.php
  tests/front/controller/admin/ShaareManageControllerTest/ChangeVisibilityBookmarkTest.php
  tests/front/controller/admin/ShaareManageControllerTest/DeleteBookmarkTest.php
  tests/front/controller/admin/ShaareManageControllerTest/PinBookmarkTest.php
  tests/front/controller/admin/ShaareManageControllerTest/SharePrivateTest.php
  tests/front/controller/admin/ShaarePublishControllerTest/DisplayCreateBatchFormTest.php
  tests/front/controller/admin/ShaarePublishControllerTest/DisplayCreateFormTest.php
  tests/front/controller/admin/ShaarePublishControllerTest/DisplayEditFormTest.php
  tests/front/controller/admin/ShaarePublishControllerTest/SaveBookmarkTest.php
  tpl/default/addlink.html
  tpl/default/editlink.batch.html
  tpl/default/editlink.html
  webpack.config.js
Labels: feature, in review, please test

#1612 Include php-simplexml in Docker image
  Dockerfile
Labels: docker, server

#1613 Raise 404 error instead of 500 if permalink access is denied
  application/bookmark/BookmarkFileService.php
  tests/bookmark/BookmarkFileServiceTest.php
Labels: enhancement, security

#1614 Fix compatiliby issue on login with PHP 7.1
  application/render/PageBuilder.php
  application/security/SessionManager.php
Labels: bug, php compatibility

#1615 Remove unnecessary escape of referer
  application/front/controller/admin/ShaarePublishController.php
Labels: bug

#1616 API postLink: change relative path to absolute path
  application/api/controllers/Links.php
  tests/api/controllers/links/PostLinkTest.php
Labels: API, bug
