Repository shaarli/Shaarli, pull requests merged in 2020-06, with the labels that each got.

#1426 V0.11 fixes one error on 'daily' page & a malfunction for local link in Markdown render
  application/http/UrlUtils.php
  index.php
Labels: bug

#1476 Fix missing php7-simplexml plugin for Dockerfile.armhf
  Dockerfile.armhf
Labels: docker, in review

#1428 ldap authentication, fixes shaarli/Shaarli#1343
  application/security/LoginManager.php
  doc/md/Shaarli-configuration.md
  tests/security/LoginManagerTest.php
Labels: feature, in review
