Repository shaarli/Shaarli, pull requests merged in 2020-11, with the labels that each got.

#1618 UT: fix formatting issue when the current day has a single digit
  tests/front/controller/visitor/DailyControllerTest.php
  tests/helper/DailyPageHelperTest.php
Labels: bug

#1610 Plugin wallabag: minor improvements
  plugins/wallabag/wallabag.php
  tests/plugins/PluginWallabagTest.php
Labels: enhancement, in review, plugin

#1619 Fix French translation
  inc/languages/fr/LC_MESSAGES/shaarli.po
Labels: translations

#1624 Fix: redirect to referrer after bookmark deletion
  application/front/controller/admin/ShaareManageController.php
  tests/front/controller/admin/ShaareManageControllerTest/DeleteBookmarkTest.php
Labels: bug

#1620 Default formatter: add a setting to disable auto-linkification
  application/bookmark/LinkUtils.php
  application/formatter/BookmarkDefaultFormatter.php
  doc/md/Shaarli-configuration.md
  tests/formatter/BookmarkDefaultFormatterTest.php
Labels: enhancement

#1625 Fix confirm popup before bookmark deletion
  assets/default/js/base.js
  inc/languages/fr/LC_MESSAGES/shaarli.po
  tpl/default/changetag.html
  tpl/default/page.footer.html
Labels: bug

#1626 Webpack: fix vintage theme images include
  webpack.config.js
Labels: bug, template

#1627 Display error details even with dev.debug set to false
  application/front/controller/visitor/ErrorController.php
  assets/default/scss/shaarli.scss
  inc/languages/fr/LC_MESSAGES/shaarli.po
  tests/front/controller/visitor/ErrorControllerTest.php
  tpl/default/error.html
Labels: enhancement, in review

#1631 Fix an issue truncating extracted metadata content
  application/bookmark/LinkUtils.php
  tests/bookmark/LinkUtilsTest.php
Labels: bug

#1629 Replace vimeo link in demo bookmarks due to IP ban on the demo instance
  application/bookmark/BookmarkInitializer.php
Labels: project-related

#1621 Feature: support any tag separator
  application/bookmark/Bookmark.php
  application/bookmark/BookmarkFileService.php
  application/bookmark/BookmarkFilter.php
  application/bookmark/LinkUtils.php
  application/config/ConfigManager.php
  application/formatter/BookmarkDefaultFormatter.php
  application/formatter/BookmarkFormatter.php
  application/front/controller/admin/ManageTagController.php
  application/front/controller/admin/ShaareManageController.php
  application/front/controller/admin/ShaarePublishController.php
  application/front/controller/visitor/BookmarkListController.php
  application/front/controller/visitor/TagCloudController.php
  application/front/controller/visitor/TagController.php
  application/http/HttpAccess.php
  application/http/HttpUtils.php
  application/http/MetadataRetriever.php
  application/legacy/LegacyUpdater.php
  application/netscape/NetscapeBookmarkUtils.php
  application/render/PageBuilder.php
  assets/default/js/base.js
  assets/default/scss/shaarli.scss
  assets/vintage/js/base.js
  composer.json
  composer.lock
  doc/md/Shaarli-configuration.md
  index.php
  tests/bookmark/BookmarkFilterTest.php
  tests/bookmark/BookmarkTest.php
  tests/bookmark/LinkUtilsTest.php
  tests/front/controller/admin/ManageTagControllerTest.php
  tests/front/controller/admin/ShaarePublishControllerTest/DisplayCreateFormTest.php
  tests/front/controller/admin/ShaarePublishControllerTest/DisplayEditFormTest.php
  tests/front/controller/visitor/BookmarkListControllerTest.php
  tests/front/controller/visitor/FrontControllerMockHelper.php
  tests/front/controller/visitor/TagCloudControllerTest.php
  tests/front/controller/visitor/TagControllerTest.php
  tests/netscape/BookmarkImportTest.php
  tpl/default/changetag.html
  tpl/default/linklist.html
  tpl/default/page.footer.html
  tpl/default/tag.cloud.html
  tpl/vintage/includes.html
  tpl/vintage/linklist.html
  tpl/vintage/page.footer.html
Labels: feature, in review, tags

#1628 Reviewed nginx configuration
  .docker/nginx.conf
  .dockerignore
  doc/md/Server-configuration.md
Labels: bug, documentation, in review, security, server

#1634 Docker-compose: fix SSL certificate + add parameter for Docker tag
  doc/md/Docker.md
  docker-compose.yml
Labels: bug, docker, in review

#1630 Reviewed Apache configuration
  .htaccess
  doc/md/Server-configuration.md
Labels: documentation, in review, please test, server

#1636 Fix a few compatibility issues with the vintage theme
  assets/vintage/css/shaarli.css
  tpl/vintage/daily.html
  tpl/vintage/editlink.html
  tpl/vintage/page.header.html
Labels: in review, template

#1637 Server admin: do not retrieve latest version without update_check
  application/config/ConfigManager.php
  application/front/controller/admin/ServerController.php
  inc/languages/fr/LC_MESSAGES/shaarli.po
Labels: cleanup, enhancement, in review

#1638 CHANGELOG v0.12.1
  AUTHORS
  CHANGELOG.md
Labels: project-related

#1639 Doc: fix missing merge on Release page
  doc/md/dev/Release-Shaarli.md
Labels: documentation, tools

#1642 Add Russian translation
  application/Languages.php
  inc/languages/ru/LC_MESSAGES/shaarli.po
Labels: translations

#1648 ConfigureControllerTest.php: update expected languages number to 6
  inc/languages/ru/LC_MESSAGES/shaarli.po
  tests/front/controller/admin/ConfigureControllerTest.php
Labels: bug
