Repository shaarli/Shaarli, pull requests merged in 2021-05, with the labels that each got.

#1748 Fix documentation build
  doc/custom_theme/main.html
  mkdocs.yml
Labels: bug, dependencies, documentation

#1741 switch continuous integration system to Drone CI
  .drone.yml
  .travis.yml
  README.md
  doc/md/dev/Development.md
Labels: cleanup, in review, php compatibility, tools

#1752 Update includes.html
  tpl/vintage/includes.html
Labels: bug, template

#1759 Setup Github Actions for Shaarli
  .drone.yml
  .github/workflows/ci.yml
Labels: project-related, tools

#1760 Change Zeichen to Token
  inc/languages/de/LC_MESSAGES/shaarli.po
Labels: in review, translations
