Repository shaarli/Shaarli, pull requests merged in 2021-03, with the labels that each got.

#1717 Fix typo in documentation
  doc/md/Docker.md
Labels: documentation

#1722 Bump WebThumbnailer version to fix Instagram issue
  composer.lock
Labels: 3rd party

#1718 doc: apache: explicitly set index.php as DirectoryIndex
  doc/md/Server-configuration.md
Labels: documentation, server
