Repository shaarli/Shaarli, pull requests merged in 2021-04, with the labels that each got.

#1725 Fix a crash when generating an atom feed with no bookmarks
  application/bookmark/BookmarkFileService.php
Labels: bug

#1731 Search highlight: do not use special characters for tokens
  application/formatter/BookmarkDefaultFormatter.php
Labels: bug

#1732 Change legacy URL route for Add Note bookmarklet
  tpl/default/tools.html
  tpl/vintage/tools.html
Labels: template

#1734 Documentation: include all PHP extensions installed in our official Docker image
  doc/md/Server-configuration.md
Labels: documentation, in review

#1738 doc: plugins.md: fix link casing
  doc/md/Plugins.md
Labels: bug, documentation

#1739 Add '406 not acceptable' to the Troubleshooting section
  doc/md/Troubleshooting.md
Labels: documentation
