Repository shaarli/Shaarli, pull requests merged in 2021-01, with the labels that each got.

#1672 API: POST/PUT Link - properly parse tags string
  application/api/ApiUtils.php
  application/api/controllers/Links.php
  tests/api/controllers/links/PostLinkTest.php
  tests/api/controllers/links/PutLinkTest.php
Labels: API, enhancement, in review

#1671 Fix default_colors plugin: update CSS file on color change
  plugins/default_colors/default_colors.php
  tests/plugins/PluginDefaultColorsTest.php
Labels: bug, in review, plugin

#1675 Update Japanese translations
  inc/languages/jp/LC_MESSAGES/shaarli.po
Labels: translations

#1687 Inject current template name in templates
  application/front/controller/visitor/ShaarliVisitorController.php
  tests/front/controller/visitor/ShaarliVisitorControllerTest.php
Labels: enhancement, template

#1689 Fix: bulk add - use unique HTML ID
  tpl/default/editlink.batch.html
  tpl/default/editlink.html
Labels: bug, template

#1691 Fix: bulk add - private status
  assets/common/js/shaare-batch.js
Labels: bug, javascript

#1693 Fix: bulk add - delete existing link
  application/front/controller/admin/ShaareManageController.php
  assets/common/js/shaare-batch.js
  tests/front/controller/admin/ShaareManageControllerTest/DeleteBookmarkTest.php
Labels: bug

#1695 curl usage: support HTTP/2 response code header
  application/Utils.php
  application/helper/ApplicationUtils.php
Labels: enhancement

#1699 Update German translations, added new strings to server.html
  inc/languages/de/LC_MESSAGES/shaarli.po
  tpl/default/server.html
Labels: translations

#1694 Fix: bulk add redirection with ending slash
  assets/common/js/shaare-batch.js
Labels: bug, javascript
