Repository shaarli/Shaarli, pull requests merged in 2021-09, with the labels that each got.

#1791 Intuitive checkbox for Enabled Plugins
  tpl/default/pluginsadmin.html
  tpl/vintage/pluginsadmin.html
Labels: ergonomy

#1786 remove travis from README.md
  README.md
Labels: project-related, documentation

#1798 OR tag search
  .gitignore
  application/bookmark/BookmarkFilter.php
  assets/default/js/base.js
  doc/md/Usage.md
  tests/bookmark/BookmarkFilterTest.php
Labels: feature
