Repository shaarli/Shaarli, pull requests merged in 2022-11, with the labels that each got.

#1905 autocapitalize off for the username input
  tpl/default/install.html
  tpl/default/loginform.html
  tpl/default/page.header.html
  tpl/vintage/install.html
  tpl/vintage/loginform.html
Labels: enhancement

#1909 Fix mishandling of Shaare term
  inc/languages/de/LC_MESSAGES/shaarli.po
Labels: translations

#1915 Fix PHP 8 incompatibility with debug mode enabled
  index.php
Labels: php compatibility

#1913 Add an additional free disk space check before saving the datastore
  application/bookmark/BookmarkIO.php
  application/bookmark/exception/InvalidWritableDataException.php
  application/bookmark/exception/NotEnoughSpaceException.php
Labels: enhancement, in review, server

#1877 PubSubHub Plugin: make 1 external call per request
  plugins/pubsubhubbub/pubsubhubbub.php
Labels: plugin, performance

#1898 Bulk action: add or delete tag to multiple bookmarks
  application/bookmark/Bookmark.php
  application/front/controller/admin/ShaareManageController.php
  assets/default/js/base.js
  index.php
  tests/front/controller/admin/ShaareManageControllerTest/AddOrDeleteTagTest.php
  tpl/default/page.header.html
Labels: feature, tags

#1914 docker: install php8-ldap in Docker images
  Dockerfile
  Dockerfile.armhf
Labels: enhancement, in review, docker

#1916 Fix ReadItLater checkbox label on bulk add
  plugins/readitlater/readitlater.php
  plugins/readitlater/readitlater_editlink.html
  tests/plugins/PluginReadItLaterTest.php
Labels: plugin, template

#1917 fix: bulk tag action - wrong controller name
  index.php
  tpl/default/page.header.html
Labels: bug
