Repository shaarli/Shaarli, pull requests merged in 2022-08, with the labels that each got.

#1867 Dockerfile/Dockerfile.armhf: update base alpine image to v3.16
  Dockerfile
  Dockerfile.armhf
  doc/md/dev/Unit-tests.md
  tests/docker/alpine316/Dockerfile
Labels: docker, dependencies

#1871 chore: bump minor composer dependencies
  composer.lock
Labels: php compatibility, dependencies

#1788 trivial refine for messages
  application/front/controller/admin/ShaarliAdminController.php
  application/security/SessionManager.php
  doc/md/Backup-and-restore.md
  doc/md/dev/Development.md
  doc/md/dev/Unit-tests.md
  plugins/wallabag/wallabag.php
  tpl/default/configure.html
  tpl/default/install.html
  tpl/default/pluginsadmin.html
  tpl/default/tools.html
Labels: translations

#1792 Simple and uniform localized website title
  application/front/controller/visitor/InstallController.php
  tests/front/controller/visitor/InstallControllerTest.php
Labels: enhancement

#1787 refine Community-and-related-software.md and tools page
  doc/md/Community-and-related-software.md
  mkdocs.yml
  tpl/default/tools.html
Labels: documentation

#1727 New Core Plugin: ReadItLater
  application/bookmark/Bookmark.php
  application/bookmark/BookmarkFilter.php
  application/formatter/BookmarkDefaultFormatter.php
  application/formatter/BookmarkFormatter.php
  application/front/controller/admin/ShaareManageController.php
  application/plugin/PluginManager.php
  composer.json
  doc/md/Plugins.md
  plugins/readitlater/ReadItLaterController.php
  plugins/readitlater/readitlater.default.css
  plugins/readitlater/readitlater.default.js
  plugins/readitlater/readitlater.meta
  plugins/readitlater/readitlater.php
  plugins/readitlater/readitlater_button.html
  plugins/readitlater/readitlater_editlink.html
  tests/bookmark/BookmarkFileServiceTest.php
  tests/formatter/BookmarkDefaultFormatterTest.php
  tests/formatter/BookmarkMarkdownFormatterTest.php
  tests/front/controller/admin/ShaareManageControllerTest/SharePrivateTest.php
  tests/plugins/PluginReadItLaterTest.php
  tests/plugins/test_route_invalid/test_route_invalid.php
Labels: plugin, feature, in review

#1872 Netscape bookmark parser: bump to new major version
  application/netscape/NetscapeBookmarkUtils.php
  composer.json
  composer.lock
Labels: enhancement, 3rd party

#1878 Github Action: fix failing pipeline due to rate limit on githubassets.com
  tests/ThumbnailerTest.php
Labels: tools, 3rd party
