Repository shaarli/Shaarli, pull requests merged in 2022-12, with the labels that each got.

#1918 Ensure tags are unique when adding and deleting them from bookmarks.
  application/bookmark/Bookmark.php
  tests/bookmark/BookmarkTest.php
Labels: bug, tags

#1921 doc: usage.md: add note about batch/bulk creation operation
  doc/md/Usage.md
Labels: documentation

#1922 doc: PHP extensions are also required for development
  doc/md/dev/Unit-tests.md
Labels: documentation, tools

#1926 Add mention to Shaarli Archiver
  doc/md/Community-and-related-software.md
Labels: documentation
