Repository shaarli/Shaarli, pull requests merged in 2022-09, with the labels that each got.

#1858 doc: shaarli configuration: fixes/improvements to thumbnails settings documentation
  doc/md/Shaarli-configuration.md
Labels: documentation

#1866 Resolve PHP 8.1 deprecations
  application/Utils.php
  application/api/controllers/HistoryController.php
  application/bookmark/BookmarkArray.php
  application/bookmark/LinkUtils.php
  application/formatter/BookmarkDefaultFormatter.php
  application/front/controller/admin/ThumbnailsController.php
  application/helper/ApplicationUtils.php
  application/http/Url.php
  application/legacy/LegacyLinkDB.php
Labels: cleanup, dependencies

#1857 Improve bookmark metadata formatting for Netscape exports
  tpl/default/export.bookmarks.html
  tpl/vintage/export.bookmarks.html
Labels: enhancement, template, in review

#1869 update docker images to use PHP 8
  .docker/services.d/php-fpm/run
  Dockerfile
  Dockerfile.armhf
  Makefile
  tests/docker/alpine316/Dockerfile
Labels: bug, docker, dependencies

#1891 tools/github actions: do not cancel all PHP jobs when a single one fails
  .github/workflows/ci.yml
Labels: tools
