Repository shaarli/Shaarli, pull requests merged in 2023-03, with the labels that each got.

#1938 doc: troubleshooting: add note to adjust proxy timeouts or PHP max execution time if encountering timeouts
  doc/md/Troubleshooting.md
Labels: documentation, proxy, performance

#1947 template/vintage: fix typo in visibility selection link
  tpl/vintage/linklist.paging.html
Labels: bug, template

#1949 ci: push container images to github registry in addition to dockerhub
  .github/workflows/docker-latest.yml
  .github/workflows/docker-tags.yml
Labels: 3rd party, docker

#1928 Github actions: update node
  .github/workflows/ci.yml
  .github/workflows/docker-latest.yml
  .github/workflows/docker-tags.yml
  doc/md/Server-configuration.md
Labels: tools, php compatibility

#1945 docker: latest: replace dev in shaarli_version.php with the latest commit hash
  .github/workflows/docker-latest.yml
Labels: tools, docker

#1950 github actions: add tests for PHP 8.2
  .github/workflows/ci.yml
Labels: tools, php compatibility

#1951 doc: move OCI images hosting to ghcr.io
  README.md
  doc/md/Docker.md
  doc/md/dev/Development.md
  docker-compose.yml
Labels: documentation, docker

#1952 Do not display deprecated warnings by default
  init.php
Labels: php compatibility

#1953 Fix a bug when using '/' as a tag separator
  application/bookmark/LinkUtils.php
  tests/bookmark/LinkUtilsTest.php
Labels: bug, tags

#1954 Fix Logger exception: gracefully handle permission issue
  index.php
Labels: enhancement, server

#1955 Rename authors makefile target to avoid conflicts with filename
  Makefile
  doc/md/dev/Release-Shaarli.md
Labels: documentation, tools

#1956 Changelog v0.12.2
  AUTHORS
  CHANGELOG.md
Labels: project-related

#1957 Makefile: Use GNU tar if available
  Makefile
  doc/md/dev/Release-Shaarli.md
Labels: tools

#1960 doc: update release procedure (merge the latest release to the release branch) + use the release branch for latest release version detection
  application/front/controller/admin/ServerController.php
  application/legacy/LegacyUpdater.php
  doc/md/dev/Release-Shaarli.md
Labels: project-related, documentation

#1962 github actions: build OCI images that contain both amd64 and armv7
  .github/workflows/docker-latest.yml
  .github/workflows/docker-tags.yml
  Dockerfile.armhf
Labels: enhancement, docker

#1965 Docker build: add ARM64 platform and bump Github action version
  .github/workflows/docker-latest.yml
Labels: docker
