Repository shaarli/Shaarli, pull requests merged in 2023-11, with the labels that each got.

#2028 Add shaarli-stack theme to Community-and-related-software.md
  doc/md/Community-and-related-software.md
Labels: documentation, 3rd party

#2030 doc: themes: remove unmaintained themes
  doc/md/Community-and-related-software.md
Labels: documentation, 3rd party

#2035 doc: remove bountysource badge
  README.md
Labels: documentation

#2036 doc: document general.download_max_size/timeout configuration settings
  doc/md/Shaarli-configuration.md
Labels: documentation

#2037 doc: troubleshooting: automatic title retrieval fails when it is set by javascript
  doc/md/Troubleshooting.md
Labels: documentation

#2039 Fix XSS vulnerability in tag search
  application/front/controller/visitor/BookmarkListController.php
Labels: security, in review

#2040 Changelog v0.13.0 + authors
  AUTHORS
  CHANGELOG.md
Labels: project-related

#2041 Bump badge version in README
  README.md
Labels: project-related

#1971 Remove 'updates.check_updates_branch' setting
  application/config/ConfigManager.php
  application/front/controller/admin/ServerController.php
  application/helper/ApplicationUtils.php
  application/render/PageBuilder.php
  application/updater/Updater.php
  doc/md/Shaarli-configuration.md
  tests/helper/ApplicationUtilsTest.php
  tests/utils/config/configJson.json.php
Labels: project-related, documentation, in review

#2044 PHP 8.x intl incompatibility: failback C locale with en_US
  application/Utils.php
  application/front/controller/visitor/FeedController.php
  application/http/HttpUtils.php
  index.php
  tests/languages/de/UtilsDeTest.php
  tests/languages/en/UtilsEnTest.php
  tests/languages/fr/UtilsFrTest.php
Labels: tools, php compatibility
