Repository shaarli/Shaarli, pull requests merged in 2023-12, with the labels that each got.

#2047 github actions: run daily trivy security scans on release docker image, composer/yarn dependencies
  .github/workflows/trivy-release.yml
  Makefile
  README.md
Labels: enhancement, security, tools, in review, docker, dependencies

#2043 github actions: don't attempt to push docker image from forks
  .github/workflows/docker-latest.yml
  .github/workflows/docker-tags.yml
Labels: tools

#2059 Documentation: fix broken link to 3rd party plugins
  tpl/default/tools.html
Labels: bug, documentation, tools

#2056 frontend: update npm dependencies (npm audit fix)
  yarn.lock
Labels: security, dependencies
