Repository shaarli/Shaarli, pull requests merged in 2023-07, with the labels that each got.

#1998 tools/CI: scan repository with trivy security scanner (yarn.lock, composer.lock)
  .github/workflows/ci.yml
  .github/workflows/docker-latest.yml
  .gitignore
  Makefile
Labels: security, tools

#2005 tools/Makefile: update trivy to v0.43.1
  Makefile
Labels: tools

#2008 Doc update, WebSub (formerly PubSubHubbub) plugin
  plugins/pubsubhubbub/README.md
Labels: documentation
