Repository shaarli/Shaarli, pull requests merged in 2023-05, with the labels that each got.

#1984 Update Community-and-related-software.md
  doc/md/Community-and-related-software.md
Labels: documentation, 3rd party

#1980 tools: run trivy vulnerability scanner on the 'latest' docker image
  .github/workflows/docker-latest.yml
  Makefile
Labels: security, tools, docker

#1987 doc: improve docs on usage of OR operator in tags search
  doc/md/Usage.md
Labels: enhancement, documentation

#1989 gihub actions: fix value of TRIVY_TARGET_DOCKER_IMAGE
  .github/workflows/docker-latest.yml
Labels: bug, tools
