Repository shaarli/Shaarli, pull requests merged in 2024-11, with the labels that each got.

#2096 doc: usage: add opensearch/browser search engine integration instructions
  doc/md/Usage.md
Labels: documentation

#2086 2084: Ensure tags are unique when renaming
  application/bookmark/Bookmark.php
  tests/bookmark/BookmarkTest.php
  tests/front/controller/admin/ManageTagControllerTest.php
Labels: bug, in review

#2101 dependencies: update npm dependencies (npm audit fix)
  package.json
  yarn.lock
Labels: security, dependencies

#2106 doc: changelog: minor style tweaks/standardization/spacing
  CHANGELOG.md
Labels: documentation

#2107 doc: changelog: fix link to v0.13.0 release
  CHANGELOG.md
Labels: documentation
