Repository shaarli/Shaarli, pull requests merged in 2024-10, with the labels that each got.

#2087 #2052: update vulnerable npm dependencies (npm audit fix)
  .dev/.stylelintrc.js
  .github/workflows/ci.yml
  .github/workflows/docker-latest.yml
  .github/workflows/docker-pr.yml
  .github/workflows/docker-tags.yml
  .github/workflows/trivy-release.yml
  Dockerfile
  assets/default/scss/shaarli.scss
  doc/md/dev/Development.md
  package.json
  tests/docker/alpine319/Dockerfile
  webpack.config.js
  yarn.lock
Labels: security, in review, dependencies

#2088 docker: update base alpine linux image to v3.19.4
  Dockerfile
  doc/md/dev/Development.md
  tests/docker/alpine319/Dockerfile
Labels: docker, dependencies

#2100 tools/tests: update trivy vulnerability scanner to v0.56.2
  Makefile
Labels: security, tools, dependencies

#2102 fix wrong date format when language is not english (Alpine icu package split)
  Dockerfile
Labels: bug
