Repository shaarli/Shaarli, pull requests merged in 2025-04, with the labels that each got.

#2123 docker: update base alpine image to v3.19.7
  Dockerfile
  tests/docker/alpine319/Dockerfile
Labels: docker, dependencies

#2140 update packages and phpunit
  composer.lock
  package.json
  phpunit.xml
  yarn.lock
Labels: dependencies

#2109 Keep private links number … private.
  application/front/controller/visitor/ShaarliVisitorController.php
  tpl/default/linklist.html
  tpl/vintage/page.header.html
Labels: enhancement

#2143 github actions: workaround for ondrej/php apt repository update error
  .github/workflows/ci.yml
Labels: bug, tools

#2144 github actions: pin all base images to ubuntu-24.04
  .github/workflows/ci.yml
  .github/workflows/docker-latest.yml
  .github/workflows/docker-pr.yml
  .github/workflows/docker-tags.yml
  .github/workflows/trivy-release.yml
Labels: bug, tools

#2138 Refactor video plugin
  plugins/playvideos/README.md
  plugins/playvideos/jquery-1.11.2.js
  plugins/playvideos/jquery-1.11.2.min.js
  plugins/playvideos/playvideos.php
  plugins/playvideos/youtube_playlist.js
  tests/plugins/PluginPlayvideosTest.php
Labels: enhancement, plugin, cleanup, in review, javascript
