Repository shaarli/Shaarli, pull requests merged in 2025-03, with the labels that each got.

#2132 Community: Added colorscheme and youtube plugins, and shirley-template
  doc/md/Community-and-related-software.md
Labels: plugin, documentation, 3rd party

#2125 Fix "PHP message: TypeError: get_headers(): Argument #2 ($associative…
  application/http/HttpUtils.php
Labels: bug

#2135 tests: fix CI and translation tests
  .github/act/Dockerfile
  .github/workflows/ci.yml
  Makefile
  composer.json
  composer.lock
  tests/languages/en/UtilsEnTest.php
Labels: bug, tools, in review
